"""Added song table

Revision ID: df416969bb3c
Revises: 
Create Date: 2022-01-28 16:59:52.730200

"""
import sqlalchemy as sa
from alembic import op

from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df416969bb3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=768), nullable=True),
    sa.Column('url', mysql.VARCHAR(length=768), nullable=True),
    sa.Column('keywords', mysql.VARCHAR(length=768), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_songs_updated_at'), 'songs', ['updated_at'], unique=False)
    op.create_index(op.f('ix_songs_url'), 'songs', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_songs_url'), table_name='songs')
    op.drop_index(op.f('ix_songs_updated_at'), table_name='songs')
    op.drop_table('songs')
    # ### end Alembic commands ###
